apiVersion: v1
kind: ConfigMap
metadata:
  name: confmap-1
  namespace: ml
data:
  MONGO_DB: "mlops_project_database"
  COLLECTION_2: "corrections"
  BUCKET_1: "mlops-476802-bucket-1"
  BUCKET_2: "mlops-476802-bucket-2"
  BUCKET_3: "gs://mlops-476802-bucket-3" #Since this is getting used in the mlflow server for artifact root
  BATCH_SIZE: "50"
  TRAIN_TEST_SPLIT: "0.7"
  POSTGRESQL_URI: "postgresql://mlflow_user:mypostgresql@10.72.0.3:5432/mlflowdb"
